inherits:
  - duplicated
  - utils:base
  - utils:fix
  - utils:no-design-checks

ignore-patterns:
  - jsonschema_gentypes/configuration.py
  - jsonschema_gentypes/jsonschema_draft_.*\.py
  - tests/openapi3\.py

mypy:
  options:
    python-version: '3.9'

ruff:
  options:
    target-version: py39
