strictness: veryhigh
doc-warnings: true

ignore-paths:
  - build

pep257:
  disable:
    - D212 # Multi-line docstring summary should start at the first line
    - D407 # Missing dashed underline after section
    - D413 # Missing blank line after last section
    - D200 # One-line docstring should fit on one line with quotes
    - D203 # 1 blank line required before class
    - D202 # No blank lines allowed after function docstring

pylint:
  disable:
    - wrong-import-order
    - too-many-arguments
    - too-many-branches
    - too-many-locals
    - too-many-statements
    - too-many-nested-blocks
    - too-many-return-statements
    - too-few-public-methods
    - no-else-return
    - line-too-long

pep8:
  disable:
    - E203 # whitespace before ':'
    - E501 # line too long

mypy:
  run: true

mccabe:
  run: false
