inherits:
  - duplicated
  - duplicated
strictness: veryhigh
doc-warnings: true
max-line-length: 110

ignore-patterns:
  - jsonschema_gentypes/configuration.py
  - jsonschema_gentypes/jsonschema_draft_.*\.py

pydocstyle:
  disable:
    - D212 # Multi-line docstring summary should start at the first line
    - D407 # Missing dashed underline after section
    - D200 # One-line docstring should fit on one line with quotes
    - D203 # 1 blank line required before class
    - D202 # No blank lines allowed after function docstring

pylint:
  disable:
    - too-many-arguments
    - too-many-branches
    - too-many-locals
    - too-many-statements
    - too-many-nested-blocks
    - too-many-return-statements
    - too-many-lines
    - too-few-public-methods
    - no-else-return
    - line-too-long # in conflict with Black

pycodestyle:
  disable:
    - E501 # line too long, duplicated with Pylint
    - N806 # variable in function should be lowercase, duplicated with Pylint

mypy:
  run: true

bandit:
  run: true
  options:
    config: .bandit.yaml

pyroma:
  run: true

mccabe:
  run: false
